#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Feb  8 11:38:24 2020

@author: balthasar
"""

conversion = {'gluten free chicken broth':'broth',
'sodium free chicken broth':'broth',
'mushroom broth':'broth',
'regular chicken broth':'broth',
'reduced sodium canned chicken broth':'broth',
'low sodium fat free vegetable broth':'broth',
'low sodium canned chicken broth':'broth',
'sodium reduced chicken broth':'broth',
'sodium reduced beef broth':'broth',
'organic low sodium chicken broth':'broth',
'low sodium low fat vegetable broth':'broth',
'gluten-free broth':'broth',
'less sodium fat free chicken broth':'broth',
'one third less sodium chicken broth':'broth',
'low-fat chicken broth':'broth',
'low-sodium low-fat chicken broth':'broth',
'fat free less sodium vegetable broth':'broth',
'less sodium chicken broth':'broth',
'low sodium broth':'broth',
'chicken broth low fat':'broth',
'swanson beef broth':'broth',
'fish broth':'broth',
'swanson chicken broth':'broth',
'25% less sodium chicken broth':'broth',
'nonfat chicken broth':'broth',
'reduced sodium fat free chicken broth':'broth',
'low fat low sodium chicken broth':'broth',
'progresso reduced sodium chicken broth':'broth',
'fat skimmed reduced sodium chicken broth':'broth',
'fat free reduced sodium chicken broth':'broth',
'bone broth':'broth',
'reduced sodium vegetable broth':'broth',
'turkey broth':'broth',
'homemade chicken broth':'broth',
'fat free beef broth':'broth',
'fat-free reduced-sodium chicken broth':'broth',
'organic chicken broth':'broth',
'condensed chicken broth':'broth',
'fatfree lowsodium chicken broth':'broth',
'store bought low sodium chicken broth':'broth',
'no salt added chicken broth':'broth',
'lower sodium beef broth':'broth',
'reduced sodium beef broth':'broth',
'fat free less sodium beef broth':'broth',
'less sodium beef broth':'broth',
'low-sodium fat-free chicken broth':'broth',
'canned beef broth':'broth',
'low sodium vegetable broth':'broth',
'low sodium beef broth':'broth',
'canned chicken broth':'broth',
'fat-free chicken broth':'broth',
'organic vegetable broth':'broth',
'lower sodium chicken broth':'broth',
'fat skimmed chicken broth':'broth',
'canned low sodium chicken broth':'broth',
'reduced sodium chicken broth':'broth',
'low sodium chicken broth':'broth',
'beef broth':'broth',
'low salt chicken broth':'broth',
'vegetable broth':'broth',
'fat free less sodium chicken broth':'broth',
'chicken broth':'broth'}